const CIBJO_SOURCE = {
  title: "The Gemstone Book",
  organization: "CIBJO – The World Jewellery Confederation",
  url: "https://cibjo.org/wp-content/uploads/2022/08/CIBJO-Gemstone-Blue-Book-2020-12-01.pdf",
  note: "Nomenclatura, dichiarazione dei trattamenti, sintetici, imitazioni e materiali compositi."
};

const GIA_SOURCE = {
  title: "GIA Gem Encyclopedia and Gem Identification Research",
  organization: "Gemological Institute of America",
  url: "https://www.gia.edu/gem-encyclopedia",
  note: "Proprietà gemmologiche, formazione, usi, trattamenti e criteri di identificazione."
};

const GEM_A_SOURCE = {
  title: "The Journal of Gemmology and gem-testing references",
  organization: "Gem-A – Gemmological Association of Great Britain",
  url: "https://gem-a.com/publications/journal-of-gemmology/",
  note: "Metodi strumentali, limiti del rifrattometro e procedure di identificazione."
};

const PROFILE_DEFINITIONS = {
  diamond: {
    family: "Carbonio nativo",
    formula: "C",
    crystal: "Cubico",
    mohs: [10, 10],
    density: [3.50, 3.53],
    ri: [2.417, 2.417],
    optical: "Isotropo; possibili anomalie da tensione",
    birefringence: "0",
    dispersion: "0,044",
    pleochroism: "Assente",
    fluorescence: "Variabile; spesso blu in UV lunga, ma non diagnostica da sola",
    tenacity: "Fragile con elevata resistenza all'abrasione",
    cleavage: "Perfetta ottaedrica",
    fracture: "Concoide o irregolare",
    luster: "Adamantino",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Tester termico per diamanti", "Tester elettrico/moissanite", "Microscopio gemmologico", "Lampada UV corta onda"],
    inclusions: "Cristalli, piume, nuvole o graining; la morfologia va interpretata insieme a crescita e risposta strumentale.",
    treatments: ["Irraggiamento e ricottura", "HPHT per modifica del colore", "Riempimento di fratture", "Foratura laser"],
    simulants: ["Moissanite", "Zirconia cubica", "Zircone", "Vetro"],
    compare: "Moissanite, zirconia cubica e diamante prodotto in laboratorio",
    cleaning: "Evitare urti lungo i piani di sfaldatura; verificare riempimenti prima di ultrasuoni, vapore o calore."
  },
  moissanite: {
    family: "Carburi",
    formula: "SiC",
    crystal: "Esagonale, politipi sintetici",
    mohs: [9.25, 9.25],
    density: [3.20, 3.24],
    ri: [2.648, 2.691],
    optical: "Uniassico positivo",
    birefringence: "0,043",
    dispersion: "0,104",
    pleochroism: "Debole o non evidente nelle qualità incolori",
    fluorescence: "Variabile; possibili reazioni arancio, gialle o verdi",
    tenacity: "Buona, con possibile scheggiatura",
    cleavage: "Indistinta",
    fracture: "Concoide",
    luster: "Adamantino",
    transparency: "Trasparente",
    tools: ["Lente 10x", "Tester termico per diamanti", "Tester elettrico/moissanite", "Microscopio gemmologico", "Polariscopio"],
    inclusions: "Tubi o aghi di crescita e raddoppio delle giunzioni di faccetta osservato da direzioni appropriate.",
    treatments: ["Possibili modifiche del colore dichiarate dal produttore"],
    simulants: ["Diamante", "Zirconia cubica", "Zircone"],
    compare: "Diamante e zirconia cubica",
    cleaning: "Pulizia delicata; evitare urti e verificare sempre la stabilità della montatura."
  },
  cubicZirconia: {
    family: "Ossidi sintetici",
    formula: "ZrO₂ stabilizzato",
    crystal: "Cubico",
    mohs: [8, 8.5],
    density: [5.65, 5.95],
    ri: [2.15, 2.18],
    optical: "Isotropo",
    birefringence: "0",
    dispersion: "0,058–0,066",
    pleochroism: "Assente",
    fluorescence: "Variabile, spesso debole o assente",
    tenacity: "Fragile",
    cleavage: "Assente",
    fracture: "Concoide",
    luster: "Adamantino a subadamantino",
    transparency: "Trasparente",
    tools: ["Lente 10x", "Tester termico per diamanti", "Bilancia idrostatica", "Microscopio gemmologico", "Polariscopio"],
    inclusions: "Materiale spesso pulito; possibili puntiformi, residui di crescita, bolle o abrasioni degli spigoli.",
    treatments: ["Rivestimenti superficiali", "Colorazione in produzione"],
    simulants: ["Diamante", "Moissanite", "Zircone", "Vetro"],
    compare: "Diamante, moissanite e vetro",
    cleaning: "Evitare abrasivi, urti e forte calore; i rivestimenti possono essere sensibili."
  },
  zircon: {
    family: "Nesosilicati",
    formula: "ZrSiO₄",
    crystal: "Tetragonale",
    mohs: [6, 7.5],
    density: [3.90, 4.73],
    ri: [1.81, 2.02],
    optical: "Uniassico positivo",
    birefringence: "0,002–0,059, variabile con metamictizzazione",
    dispersion: "0,039",
    pleochroism: "Da debole a marcato nei campioni colorati",
    fluorescence: "Variabile; giallo-arancio in alcuni campioni",
    tenacity: "Fragile",
    cleavage: "Indistinta",
    fracture: "Concoide a irregolare",
    luster: "Adamantino a vitreo",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Dicroscopio", "Spettroscopio", "Bilancia idrostatica"],
    inclusions: "Raddoppio evidente delle faccette nei campioni ad alta birifrangenza; possibili cristalli e aloni.",
    treatments: ["Riscaldamento per modificare o schiarire il colore"],
    simulants: ["Diamante", "Spinello sintetico", "Zirconia cubica"],
    compare: "Diamante, zirconia cubica e spinello",
    cleaning: "Evitare ultrasuoni, vapore, urti e sbalzi termici: gli spigoli si abrasono facilmente."
  },
  glass: {
    family: "Vetri artificiali",
    formula: "Composizione silicea variabile",
    crystal: "Amorfo",
    mohs: [5, 6],
    density: [2.20, 4.50],
    ri: [1.44, 1.90],
    optical: "Isotropo con possibili tensioni anomale",
    birefringence: "0",
    dispersion: "Variabile",
    pleochroism: "Assente",
    fluorescence: "Variabile secondo coloranti e composizione",
    tenacity: "Fragile",
    cleavage: "Assente",
    fracture: "Concoide",
    luster: "Vitreo",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Microscopio gemmologico", "Rifrattometro", "Polariscopio", "Bilancia idrostatica"],
    inclusions: "Bolle sferiche o allungate, linee di flusso, spigoli arrotondati e abrasioni.",
    treatments: ["Rivestimenti", "Foil sul retro", "Colorazione in massa"],
    simulants: ["Quarzo", "Berillo", "Corindone", "Opale"],
    compare: "Quarzo, zirconia cubica e materiale naturale imitato",
    cleaning: "Solo metodi delicati; evitare calore, ultrasuoni e solventi in presenza di foil o rivestimenti."
  },
  composite: {
    family: "Materiali assemblati",
    formula: "Variabile secondo gli strati",
    crystal: "Variabile",
    mohs: [3, 9],
    density: [2.00, 4.50],
    ri: [1.45, 1.80],
    optical: "Composto; risposta dipendente dagli strati",
    birefringence: "Variabile",
    dispersion: "Variabile",
    pleochroism: "Variabile",
    fluorescence: "Possibile risposta diversa fra strati e adesivo",
    tenacity: "Sensibile alle giunzioni",
    cleavage: "Dipende dai componenti",
    fracture: "Dipende dai componenti",
    luster: "Variabile",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Microscopio gemmologico", "Luce daylight", "Lampada UV lunga onda", "Rifrattometro"],
    inclusions: "Linea di giunzione, bolle o residui nell'adesivo, differenze di lucentezza e colore tra gli strati.",
    treatments: ["Assemblaggio con adesivo", "Foil o supporto colorato", "Rivestimenti"],
    simulants: ["Opale", "Smeraldo", "Zaffiro", "Quarzo"],
    compare: "Gemma monolitica del materiale imitato",
    cleaning: "Niente ultrasuoni, vapore, solventi o immersioni prolungate; proteggere le giunzioni."
  },
  corundum: {
    family: "Ossidi",
    formula: "Al₂O₃",
    crystal: "Trigonale",
    mohs: [9, 9],
    density: [3.95, 4.10],
    ri: [1.762, 1.778],
    optical: "Uniassico negativo",
    birefringence: "0,008–0,010",
    dispersion: "0,018",
    pleochroism: "Da debole a forte secondo colore e orientamento",
    fluorescence: "Variabile; spesso rossa nei rubini poveri di ferro",
    tenacity: "Eccellente",
    cleavage: "Assente; possibile parting",
    fracture: "Concoide a irregolare",
    luster: "Vitreo",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Dicroscopio", "Spettroscopio", "Microscopio gemmologico", "Lampada UV lunga onda"],
    inclusions: "Seta di rutilo, cristalli, impronte digitali, zoning e fratture; natura e sintesi richiedono interpretazione.",
    treatments: ["Riscaldamento", "Diffusione", "Riempimento vetroso delle fratture", "Irraggiamento in alcuni colori"],
    simulants: ["Spinello", "Granato", "Vetro", "Corindone sintetico"],
    compare: "Spinello, granato, vetro e corindone sintetico",
    cleaning: "Generalmente resistente; evitare calore, ultrasuoni e vapore se fratturato o riempito."
  },
  spinel: {
    family: "Ossidi",
    formula: "MgAl₂O₄",
    crystal: "Cubico",
    mohs: [7.5, 8],
    density: [3.58, 3.63],
    ri: [1.712, 1.736],
    optical: "Isotropo; possibili anomalie da tensione",
    birefringence: "0",
    dispersion: "0,020",
    pleochroism: "Assente",
    fluorescence: "Variabile; rosso nei campioni ricchi di cromo",
    tenacity: "Buona",
    cleavage: "Assente",
    fracture: "Concoide",
    luster: "Vitreo",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Polariscopio", "Spettroscopio", "Microscopio gemmologico"],
    inclusions: "Cristalli ottaedrici, impronte digitali, stringhe di puntiformi; sintetici possono mostrare crescita curva.",
    treatments: ["Riscaldamento occasionale", "Riempimenti rari da dichiarare"],
    simulants: ["Rubino", "Zaffiro", "Granato", "Spinello sintetico"],
    compare: "Corindone, granato e spinello sintetico",
    cleaning: "Pulizia delicata; evitare forti urti e calore su pietre fratturate."
  },
  beryl: {
    family: "Ciclosilicati",
    formula: "Be₃Al₂Si₆O₁₈",
    crystal: "Esagonale",
    mohs: [7.5, 8],
    density: [2.63, 2.92],
    ri: [1.565, 1.602],
    optical: "Uniassico negativo",
    birefringence: "0,004–0,010",
    dispersion: "0,014",
    pleochroism: "Variabile secondo colore e varietà",
    fluorescence: "Di norma debole o assente; riempimenti possono reagire",
    tenacity: "Fragile",
    cleavage: "Imperfetta basale",
    fracture: "Concoide a irregolare",
    luster: "Vitreo",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Dicroscopio", "Microscopio gemmologico", "Spettroscopio"],
    inclusions: "Cristalli, tubi di crescita, impronte digitali e inclusioni liquide; negli smeraldi sono comuni giardini complessi.",
    treatments: ["Oliatura o resine nello smeraldo", "Riscaldamento dell'acquamarina", "Irraggiamento in alcune varietà"],
    simulants: ["Vetro", "Quarzo", "Berillo sintetico", "Tormalina"],
    compare: "Quarzo, tormalina, vetro e berillo sintetico",
    cleaning: "Evitare ultrasuoni, vapore, calore e solventi per smeraldi o pietre fratturate/riempite."
  },
  quartz: {
    family: "Tettosilicati",
    formula: "SiO₂",
    crystal: "Trigonale",
    mohs: [7, 7],
    density: [2.60, 2.68],
    ri: [1.544, 1.553],
    optical: "Uniassico positivo",
    birefringence: "0,009",
    dispersion: "0,013",
    pleochroism: "Debole o assente; possibile nelle varietà colorate",
    fluorescence: "In genere debole o assente",
    tenacity: "Fragile",
    cleavage: "Assente",
    fracture: "Concoide",
    luster: "Vitreo",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Polariscopio", "Dicroscopio", "Bilancia idrostatica"],
    inclusions: "Cristalli, veli, cavità fluide, zoning e striature; geminazione osservabile con strumenti adatti.",
    treatments: ["Riscaldamento", "Irraggiamento", "Tintura", "Rivestimento"],
    simulants: ["Vetro", "Topazio", "Berillo", "Quarzo sintetico"],
    compare: "Vetro, topazio, berillo e quarzo sintetico",
    cleaning: "Evitare shock termici; trattamenti e fratture possono richiedere sola pulizia manuale."
  },
  chalcedony: {
    family: "Quarzo microcristallino",
    formula: "SiO₂",
    crystal: "Aggregato fibroso trigonale/monoclino",
    mohs: [6.5, 7],
    density: [2.55, 2.70],
    ri: [1.530, 1.540],
    optical: "Aggregato; reazione anomala",
    birefringence: "Non determinabile come singolo cristallo",
    dispersion: "Bassa",
    pleochroism: "Assente",
    fluorescence: "Variabile secondo impurità, tinture e porosità",
    tenacity: "Buona",
    cleavage: "Assente",
    fracture: "Concoide",
    luster: "Ceroso a vitreo",
    transparency: "Da traslucido a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Microscopio gemmologico", "Lampada UV lunga onda", "Spettroscopio"],
    inclusions: "Bande, tessitura fibrosa, pori, dendriti e concentrazioni di colore.",
    treatments: ["Tintura", "Riscaldamento", "Impregnazione", "Rivestimento"],
    simulants: ["Vetro", "Resina", "Quarzo ricostituito"],
    compare: "Vetro, resina e altre varietà di calcedonio",
    cleaning: "Evitare solventi, calore e ultrasuoni se tinto, impregnato o fratturato."
  },
  topaz: {
    family: "Nesosilicati",
    formula: "Al₂SiO₄(F,OH)₂",
    crystal: "Ortorombico",
    mohs: [8, 8],
    density: [3.49, 3.57],
    ri: [1.609, 1.643],
    optical: "Biassico positivo",
    birefringence: "0,008–0,011",
    dispersion: "0,014",
    pleochroism: "Da debole a moderato",
    fluorescence: "Variabile, spesso debole",
    tenacity: "Fragile",
    cleavage: "Perfetta basale",
    fracture: "Concoide a irregolare",
    luster: "Vitreo",
    transparency: "Da trasparente a traslucido",
    tools: ["Lente 10x", "Rifrattometro", "Dicroscopio", "Bilancia idrostatica", "Microscopio gemmologico"],
    inclusions: "Cristalli, cavità bifasiche, veli e fratture parallele alla sfaldatura.",
    treatments: ["Irraggiamento e riscaldamento", "Rivestimenti superficiali", "Diffusione in casi commerciali"],
    simulants: ["Quarzo", "Berillo", "Vetro", "Topazio sintetico raro"],
    compare: "Quarzo, acquamarina e vetro",
    cleaning: "Evitare urti, ultrasuoni, vapore e forti sbalzi termici per la sfaldatura perfetta."
  },
  garnet: {
    family: "Nesosilicati – gruppo dei granati",
    formula: "X₃Y₂(SiO₄)₃, composizione variabile",
    crystal: "Cubico",
    mohs: [6.5, 7.5],
    density: [3.40, 4.30],
    ri: [1.730, 1.895],
    optical: "Isotropo; possibili anomalie",
    birefringence: "0",
    dispersion: "Variabile, elevata nel demantoide",
    pleochroism: "Assente",
    fluorescence: "Generalmente debole o assente",
    tenacity: "Da discreta a buona",
    cleavage: "Assente",
    fracture: "Concoide a irregolare",
    luster: "Vitreo ad adamantino",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Spettroscopio", "Bilancia idrostatica", "Microscopio gemmologico"],
    inclusions: "Cristalli, aghi, impronte digitali; horsetail nel demantoide e inclusioni specifiche nelle diverse specie.",
    treatments: ["Trattamenti non comuni; eventuali riscaldamenti o riempimenti devono essere dichiarati"],
    simulants: ["Rubino", "Spinello", "Tormalina", "Vetro"],
    compare: "Spinello, rubino, tormalina e vetro",
    cleaning: "Pulizia delicata; evitare shock termici e ultrasuoni su pietre fratturate."
  },
  tourmaline: {
    family: "Ciclosilicati – gruppo della tormalina",
    formula: "Formula complessa a borosilicati",
    crystal: "Trigonale",
    mohs: [7, 7.5],
    density: [2.82, 3.32],
    ri: [1.603, 1.655],
    optical: "Uniassico negativo",
    birefringence: "0,014–0,032",
    dispersion: "0,017",
    pleochroism: "Spesso marcato",
    fluorescence: "Generalmente debole o assente",
    tenacity: "Fragile",
    cleavage: "Indistinta",
    fracture: "Concoide a irregolare",
    luster: "Vitreo",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Dicroscopio", "Spettroscopio", "Microscopio gemmologico"],
    inclusions: "Tubi paralleli, canali, cavità liquide, trichiti e zoning cromatico.",
    treatments: ["Riscaldamento", "Irraggiamento", "Riempimento di fratture in casi commerciali"],
    simulants: ["Berillo", "Topazio", "Vetro", "Tormalina sintetica rara"],
    compare: "Berillo, topazio, vetro e altre tormaline",
    cleaning: "Evitare calore, shock termici e ultrasuoni su pietre incluse o fratturate."
  },
  zoisite: {
    family: "Sorosilicati",
    formula: "Ca₂Al₃(SiO₄)(Si₂O₇)O(OH)",
    crystal: "Ortorombico",
    mohs: [6, 7],
    density: [3.10, 3.38],
    ri: [1.685, 1.707],
    optical: "Biassico positivo",
    birefringence: "0,006–0,018",
    dispersion: "0,030",
    pleochroism: "Forte nel blu-viola",
    fluorescence: "Generalmente debole o assente",
    tenacity: "Fragile",
    cleavage: "Perfetta in una direzione",
    fracture: "Concoide a irregolare",
    luster: "Vitreo",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Dicroscopio", "Spettroscopio", "Microscopio gemmologico"],
    inclusions: "Cristalli, aghi, cavità fluide e zoning; pleocroismo molto evidente.",
    treatments: ["Riscaldamento quasi universale per sviluppare il blu-viola"],
    simulants: ["Iolite", "Zaffiro", "Vetro"],
    compare: "Iolite, zaffiro e vetro",
    cleaning: "Evitare ultrasuoni, vapore, urti e sbalzi termici."
  },
  olivine: {
    family: "Nesosilicati",
    formula: "(Mg,Fe)₂SiO₄",
    crystal: "Ortorombico",
    mohs: [6.5, 7],
    density: [3.27, 3.48],
    ri: [1.650, 1.703],
    optical: "Biassico positivo o negativo secondo composizione",
    birefringence: "0,036–0,038",
    dispersion: "0,020",
    pleochroism: "Debole",
    fluorescence: "Di solito assente",
    tenacity: "Fragile",
    cleavage: "Indistinta",
    fracture: "Concoide",
    luster: "Vitreo",
    transparency: "Da trasparente a traslucido",
    tools: ["Lente 10x", "Rifrattometro", "Dicroscopio", "Spettroscopio", "Microscopio gemmologico"],
    inclusions: "Inclusioni discoidali lily-pad, cristalli scuri e fratture da tensione.",
    treatments: ["Nessun trattamento stabile comune; eventuali rivestimenti vanno dichiarati"],
    simulants: ["Vetro verde", "Tormalina", "Crisoberillo", "Zirconia cubica"],
    compare: "Vetro, tormalina e crisoberillo",
    cleaning: "Evitare acidi, ultrasuoni, vapore e shock termici."
  },
  chrysoberyl: {
    family: "Ossidi",
    formula: "BeAl₂O₄",
    crystal: "Ortorombico",
    mohs: [8.5, 8.5],
    density: [3.68, 3.78],
    ri: [1.746, 1.763],
    optical: "Biassico positivo",
    birefringence: "0,007–0,011",
    dispersion: "0,015",
    pleochroism: "Da moderato a forte; tricroismo nell'alessandrite",
    fluorescence: "Variabile, spesso rossa nell'alessandrite",
    tenacity: "Buona",
    cleavage: "Distinta",
    fracture: "Concoide a irregolare",
    luster: "Vitreo",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Dicroscopio", "Spettroscopio", "Luce daylight"],
    inclusions: "Seta, cristalli, cavità; fini inclusioni parallele producono gatteggiamento.",
    treatments: ["Trattamenti non comuni; eventuali riempimenti o rivestimenti devono essere dichiarati"],
    simulants: ["Quarzo a cambiamento di colore", "Zaffiro sintetico", "Vetro", "Occhio di gatto fibroso"],
    compare: "Quarzo, zaffiro sintetico e vetro",
    cleaning: "Pulizia delicata; evitare urti e calore su pietre fratturate."
  },
  opal: {
    family: "Silice idrata",
    formula: "SiO₂·nH₂O",
    crystal: "Amorfo con microsfere ordinate nel prezioso",
    mohs: [5, 6.5],
    density: [1.98, 2.25],
    ri: [1.37, 1.47],
    optical: "Isotropo o aggregato anomalo",
    birefringence: "0",
    dispersion: "Non applicabile; gioco di colore da diffrazione",
    pleochroism: "Assente",
    fluorescence: "Variabile; possibile verde, bianco o blu",
    tenacity: "Fragile e sensibile alla disidratazione",
    cleavage: "Assente",
    fracture: "Concoide",
    luster: "Vitreo a ceroso",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Microscopio gemmologico", "Rifrattometro", "Lampada UV lunga onda", "Bilancia idrostatica"],
    inclusions: "Pattern del gioco di colore, potch, matrice, crazing; nei sintetici pattern regolari e strutture colonnari.",
    treatments: ["Impregnazione", "Affumicatura", "Tintura", "Rivestimento", "Assemblaggio in doppiette/triplette"],
    simulants: ["Opale sintetico", "Vetro opalescente", "Resina", "Doppiette e triplette"],
    compare: "Opale sintetico, vetro, resina e materiali assemblati",
    cleaning: "Solo panno umido; evitare calore, secchezza prolungata, ultrasuoni, vapore, solventi e immersioni."
  },
  feldspar: {
    family: "Tettosilicati – feldspati",
    formula: "Composizione Na-K-Ca-Al-Si variabile",
    crystal: "Monoclino o triclino",
    mohs: [6, 6.5],
    density: [2.55, 2.76],
    ri: [1.518, 1.572],
    optical: "Biassico",
    birefringence: "0,005–0,012",
    dispersion: "Bassa",
    pleochroism: "Generalmente debole",
    fluorescence: "Variabile",
    tenacity: "Fragile",
    cleavage: "Perfetta in due direzioni",
    fracture: "Irregolare",
    luster: "Vitreo a perlaceo",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Polariscopio", "Dicroscopio", "Microscopio gemmologico"],
    inclusions: "Lamelle, geminazioni, exsoluzioni e strutture che producono adularescenza o labradorescenza.",
    treatments: ["Rivestimenti o impregnazioni occasionali"],
    simulants: ["Vetro", "Quarzo", "Opalite artificiale"],
    compare: "Quarzo, vetro e altri feldspati",
    cleaning: "Evitare urti, ultrasuoni, vapore e shock termici."
  },
  jadeite: {
    family: "Pirosseni",
    formula: "NaAlSi₂O₆",
    crystal: "Monoclino, aggregato granulare",
    mohs: [6.5, 7],
    density: [3.25, 3.40],
    ri: [1.654, 1.673],
    optical: "Aggregato; lettura spot tipica circa 1,66",
    birefringence: "0,013–0,020 nel cristallo",
    dispersion: "Bassa",
    pleochroism: "Debole",
    fluorescence: "Variabile; polimeri possono fluorescere",
    tenacity: "Eccezionale",
    cleavage: "Buona nel cristallo, mascherata nell'aggregato",
    fracture: "Scheggiosa",
    luster: "Vitreo a grasso",
    transparency: "Da traslucido a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Spettroscopio", "Microscopio gemmologico", "Lampada UV lunga onda"],
    inclusions: "Tessitura granulare, fibre, vene e concentrazioni di colore; polimeri e tinture richiedono verifica.",
    treatments: ["Sbiancamento e impregnazione polimerica", "Tintura", "Cera superficiale"],
    simulants: ["Nefrite", "Serpentino", "Quarzo avventurina", "Vetro"],
    compare: "Nefrite, serpentino, quarzo e vetro",
    cleaning: "Evitare calore, ultrasuoni, vapore e solventi se impregnata o tinta."
  },
  nephrite: {
    family: "Anfiboli",
    formula: "Ca₂(Mg,Fe)₅Si₈O₂₂(OH)₂",
    crystal: "Monoclino, aggregato fibroso",
    mohs: [6, 6.5],
    density: [2.90, 3.10],
    ri: [1.600, 1.627],
    optical: "Aggregato; lettura spot circa 1,61",
    birefringence: "Non determinabile nell'aggregato",
    dispersion: "Bassa",
    pleochroism: "Non evidente nell'aggregato",
    fluorescence: "Generalmente debole o assente",
    tenacity: "Eccezionale",
    cleavage: "Mascherata dall'aggregato fibroso",
    fracture: "Scheggiosa",
    luster: "Grasso a ceroso",
    transparency: "Da traslucido a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Microscopio gemmologico", "Spettroscopio", "Bilancia idrostatica"],
    inclusions: "Tessitura fibrosa feltrosa, fibre, macchie minerali e vene.",
    treatments: ["Cera", "Tintura", "Impregnazione"],
    simulants: ["Giadeite", "Serpentino", "Quarzo", "Vetro"],
    compare: "Giadeite, serpentino e quarzo",
    cleaning: "Pulizia manuale; evitare calore e solventi se tinta o impregnata."
  },
  turquoise: {
    family: "Fosfati",
    formula: "CuAl₆(PO₄)₄(OH)₈·4H₂O",
    crystal: "Triclino, aggregato microcristallino",
    mohs: [5, 6],
    density: [2.60, 2.90],
    ri: [1.610, 1.650],
    optical: "Aggregato, biassico nel cristallo",
    birefringence: "Circa 0,040 nel cristallo",
    dispersion: "Bassa",
    pleochroism: "Debole",
    fluorescence: "Da inerte a verde-giallo",
    tenacity: "Fragile a discreta",
    cleavage: "Perfetta nel cristallo, non evidente nell'aggregato",
    fracture: "Concoide",
    luster: "Ceroso",
    transparency: "Da traslucido a opaco",
    tools: ["Lente 10x", "Rifrattometro", "Microscopio gemmologico", "Lampada UV lunga onda", "Spettroscopio"],
    inclusions: "Matrice, porosità, concentrazioni di tintura e residui di impregnazione.",
    treatments: ["Impregnazione con cera o polimeri", "Tintura", "Ricostituzione", "Stabilizzazione"],
    simulants: ["Howlite tinta", "Magnesite tinta", "Vetro", "Materiale ricostituito"],
    compare: "Howlite, magnesite, vetro e turchese ricostituito",
    cleaning: "Niente ultrasuoni, vapore, calore, cosmetici o solventi; pulire con panno appena umido."
  },
  lapis: {
    family: "Roccia metamorfica a lazurite",
    formula: "Miscela mineralogica, componente principale lazurite",
    crystal: "Aggregato",
    mohs: [5, 6],
    density: [2.70, 2.90],
    ri: [1.500, 1.670],
    optical: "Aggregato",
    birefringence: "Non applicabile all'aggregato",
    dispersion: "Bassa",
    pleochroism: "Assente",
    fluorescence: "Variabile; calcite e sodalite possono reagire",
    tenacity: "Fragile a discreta",
    cleavage: "Variabile secondo i componenti",
    fracture: "Irregolare",
    luster: "Vitreo a grasso",
    transparency: "Opaco",
    tools: ["Lente 10x", "Microscopio gemmologico", "Lampada UV lunga onda", "Rifrattometro", "Spettroscopio"],
    inclusions: "Granuli blu di lazurite, calcite bianca e pirite metallica; tintura nelle fessure.",
    treatments: ["Tintura", "Cera o impregnazione", "Ricostituzione"],
    simulants: ["Sodalite", "Howlite tinta", "Vetro", "Materiale ricostituito"],
    compare: "Sodalite, vetro e lapislazzuli tinto/ricostituito",
    cleaning: "Evitare acidi, solventi, ultrasuoni, vapore e abrasivi."
  },
  malachite: {
    family: "Carbonati",
    formula: "Cu₂CO₃(OH)₂",
    crystal: "Monoclino, aggregato fibroso/bandato",
    mohs: [3.5, 4],
    density: [3.60, 4.05],
    ri: [1.655, 1.909],
    optical: "Biassico negativo; letture difficili nell'aggregato",
    birefringence: "Elevata",
    dispersion: "Bassa",
    pleochroism: "Visibile nei cristalli",
    fluorescence: "Di norma inerte",
    tenacity: "Fragile",
    cleavage: "Perfetta in una direzione",
    fracture: "Irregolare a scheggiosa",
    luster: "Setoso a vitreo",
    transparency: "Da traslucido a opaco",
    tools: ["Lente 10x", "Microscopio gemmologico", "Rifrattometro", "Bilancia idrostatica", "Luce daylight"],
    inclusions: "Bande concentriche, fibre e variazioni verde chiaro/scuro.",
    treatments: ["Impregnazione con cera o resina", "Ricostituzione"],
    simulants: ["Vetro", "Plastica", "Malachite ricostituita"],
    compare: "Vetro, plastica e materiale ricostituito",
    cleaning: "Materiale sensibile ad acidi, calore, vapore e ultrasuoni; usare solo panno morbido."
  },
  pearl: {
    family: "Materiale organico – nacre",
    formula: "CaCO₃ (aragonite) e conchiolina",
    crystal: "Aggregato organico microcristallino",
    mohs: [2.5, 4.5],
    density: [2.60, 2.85],
    ri: [1.52, 1.69],
    optical: "Aggregato",
    birefringence: "Aggregata",
    dispersion: "Non applicabile",
    pleochroism: "Assente",
    fluorescence: "Variabile secondo specie, ambiente e trattamenti",
    tenacity: "Discreta ma superficie tenera",
    cleavage: "Assente",
    fracture: "Irregolare",
    luster: "Perlaceo",
    transparency: "Da traslucido a opaco",
    tools: ["Lente 10x", "Microscopio digitale", "Lampada UV lunga onda", "Bilancia di precisione", "Strumenti avanzati di laboratorio"],
    inclusions: "Struttura superficiale, linee di crescita, nucleo e architettura interna osservabili con imaging appropriato.",
    treatments: ["Sbiancamento", "Tintura", "Irraggiamento", "Rivestimento", "Lucidatura"],
    simulants: ["Perla d'imitazione", "Conchiglia rivestita", "Vetro rivestito"],
    compare: "Perla coltivata, naturale e imitazione",
    cleaning: "Solo panno morbido appena umido; evitare acidi, cosmetici, calore, ultrasuoni e immersioni."
  },
  coral: {
    family: "Materiale organico – carbonato di calcio",
    formula: "CaCO₃ con componente organica",
    crystal: "Aggregato organico",
    mohs: [3, 4],
    density: [2.60, 2.70],
    ri: [1.486, 1.658],
    optical: "Aggregato",
    birefringence: "Aggregata",
    dispersion: "Non applicabile",
    pleochroism: "Assente",
    fluorescence: "Variabile",
    tenacity: "Fragile",
    cleavage: "Assente",
    fracture: "Irregolare",
    luster: "Vitreo a ceroso",
    transparency: "Da traslucido a opaco",
    tools: ["Lente 10x", "Microscopio gemmologico", "Lampada UV lunga onda", "Rifrattometro", "Spettroscopio"],
    inclusions: "Struttura longitudinale e granulare tipica; concentrazioni di colore possono indicare tintura.",
    treatments: ["Tintura", "Sbiancamento", "Impregnazione", "Ricostituzione"],
    simulants: ["Vetro", "Plastica", "Howlite tinta", "Corallo ricostituito"],
    compare: "Vetro, plastica e materiale ricostituito",
    cleaning: "Evitare acidi, cosmetici, calore, ultrasuoni e vapore; pulire delicatamente."
  },
  amber: {
    family: "Resina fossile organica",
    formula: "Miscela organica complessa",
    crystal: "Amorfo",
    mohs: [2, 2.5],
    density: [1.05, 1.10],
    ri: [1.539, 1.545],
    optical: "Isotropo",
    birefringence: "0",
    dispersion: "Bassa",
    pleochroism: "Assente",
    fluorescence: "Spesso blu, verde o giallastra in UV lunga",
    tenacity: "Fragile",
    cleavage: "Assente",
    fracture: "Concoide",
    luster: "Resinoso",
    transparency: "Da trasparente a opaco",
    tools: ["Lente 10x", "Microscopio gemmologico", "Lampada UV lunga onda", "Bilancia idrostatica", "Strumenti avanzati di laboratorio"],
    inclusions: "Bolle, detriti vegetali, insetti e strutture di flusso; imitazioni possono mostrare caratteristiche artificiali.",
    treatments: ["Riscaldamento", "Chiarificazione", "Pressatura", "Tintura", "Rivestimento"],
    simulants: ["Copale", "Resina sintetica", "Plastica", "Ambra pressata"],
    compare: "Copale, plastica e resina sintetica",
    cleaning: "Evitare solventi, alcol, calore, ultrasuoni e abrasivi; usare panno morbido."
  }
};

const PROFILE_BY_SLUG = {
  "diamante-naturale": "diamond",
  "diamante-sintetico-hpht": "diamond",
  "diamante-sintetico-cvd": "diamond",
  "diamante-trattato": "diamond",
  moissanite: "moissanite",
  "zirconia-cubica": "cubicZirconia",
  "zircone-naturale": "zircon",
  "vetro-pasta-vitrea": "glass",
  "doppiette-triplette": "composite",
  "rubino-naturale": "corundum",
  "rubino-sintetico": "corundum",
  "zaffiro-blu-naturale": "corundum",
  "zaffiri-fancy": "corundum",
  "zaffiro-sintetico": "corundum",
  "spinello-naturale": "spinel",
  "spinello-sintetico": "spinel",
  smeraldo: "beryl",
  "smeraldo-sintetico": "beryl",
  acquamarina: "beryl",
  morganite: "beryl",
  eliodoro: "beryl",
  goshenite: "beryl",
  ametista: "quartz",
  citrino: "quartz",
  "quarzo-ialino": "quartz",
  "quarzo-fume": "quartz",
  "quarzo-rosa": "quartz",
  prasiolite: "quartz",
  calcedonio: "chalcedony",
  agata: "chalcedony",
  onice: "chalcedony",
  topazio: "topaz",
  "topazio-imperiale": "topaz",
  "granato-almandino": "garnet",
  "granato-piropo": "garnet",
  rodolite: "garnet",
  tsavorite: "garnet",
  demantoide: "garnet",
  tormalina: "tourmaline",
  rubellite: "tourmaline",
  indicolite: "tourmaline",
  "tormalina-paraiba": "tourmaline",
  tanzanite: "zoisite",
  peridoto: "olivine",
  alessandrite: "chrysoberyl",
  "crisoberillo-occhio-di-gatto": "chrysoberyl",
  "opale-prezioso": "opal",
  "opale-di-fuoco": "opal",
  "opale-sintetico": "opal",
  "pietra-di-luna": "feldspar",
  labradorite: "feldspar",
  giadeite: "jadeite",
  nefrite: "nephrite",
  turchese: "turquoise",
  lapislazzuli: "lapis",
  malachite: "malachite",
  "perla-naturale": "pearl",
  "perla-coltivata": "pearl",
  "perla-imitazione": "pearl",
  corallo: "coral",
  ambra: "amber"
};

const VARIANT_OVERRIDES = {
  "diamante-sintetico-hpht": {
    origin: "Produzione in laboratorio con metodo HPHT",
    history: "Il metodo HPHT riproduce pressioni e temperature di crescita del diamante; l'origine richiede screening e conferma strumentale.",
    inclusions: "Possibili inclusioni metalliche, settori di crescita cubo-ottaedrici e fosforescenza; nessun singolo segno è universale."
  },
  "diamante-sintetico-cvd": {
    origin: "Produzione in laboratorio mediante deposizione chimica da fase vapore",
    history: "Il metodo CVD cresce il diamante per deposizione a strati; separazione e metodo richiedono spettroscopia o imaging avanzato.",
    inclusions: "Possibili striature planari, puntiformi grafitici e segnali di crescita; campioni puliti richiedono analisi avanzata."
  },
  "diamante-trattato": {
    origin: "Diamante naturale o sintetico sottoposto a trattamento dichiarabile",
    history: "Colore o purezza apparente possono essere modificati; foratura laser e riempimento richiedono descrizione trasparente."
  },
  "rubino-naturale": { colors: ["Rosso, rosso porpora, rosso aranciato"], origin: "Origine naturale in depositi marmorei o basaltici" },
  "rubino-sintetico": { colors: ["Rosso"], origin: "Produzione Verneuil, flux, idrotermale o altri metodi", classification: "Sintetica" },
  "zaffiro-blu-naturale": { colors: ["Blu da chiaro a scuro"], origin: "Origine naturale in depositi primari o alluvionali" },
  "zaffiri-fancy": { colors: ["Giallo, rosa, arancio, verde, viola e altri colori non blu"], origin: "Origine naturale" },
  "zaffiro-sintetico": { colors: ["Blu e altri colori"], origin: "Produzione Verneuil, flux o altri metodi", classification: "Sintetica" },
  "spinello-sintetico": { origin: "Produzione Verneuil, flux o altri metodi", classification: "Sintetica" },
  smeraldo: { colors: ["Verde, verde-bluastro"], origin: "Origine naturale in depositi idrotermali o metamorfici" },
  "smeraldo-sintetico": { colors: ["Verde"], origin: "Produzione idrotermale o flux", classification: "Sintetica" },
  acquamarina: { colors: ["Azzurro, blu-verdastro"], treatments: ["Riscaldamento per ridurre componenti verdi"] },
  morganite: { colors: ["Rosa, rosa pesca"], treatments: ["Riscaldamento", "Irraggiamento occasionale"] },
  eliodoro: { colors: ["Giallo, giallo-verde"], treatments: ["Irraggiamento o riscaldamento da dichiarare"] },
  goshenite: { colors: ["Incolore"] },
  ametista: { colors: ["Viola"], treatments: ["Riscaldamento", "Irraggiamento", "Tintura o rivestimento"] },
  citrino: { colors: ["Giallo, arancio, bruno"], treatments: ["Riscaldamento frequente di ametista", "Irraggiamento"] },
  "quarzo-ialino": { colors: ["Incolore"] },
  "quarzo-fume": { colors: ["Bruno, grigio, quasi nero"], treatments: ["Irraggiamento", "Riscaldamento"] },
  "quarzo-rosa": { colors: ["Rosa"], treatments: ["Irraggiamento o tintura non comuni"] },
  prasiolite: { colors: ["Verde chiaro"], treatments: ["Riscaldamento e/o irraggiamento"] },
  calcedonio: { colors: ["Bianco, grigio, blu, molti colori"] },
  agata: { colors: ["Bandata in numerosi colori"], treatments: ["Tintura", "Riscaldamento", "Impregnazione"] },
  onice: { colors: ["Nero e bianco bandato"], treatments: ["Tintura molto comune", "Trattamento acido-zucchero storico"] },
  "topazio-imperiale": { colors: ["Giallo-arancio, rosa-arancio, rosa"], treatments: ["Riscaldamento occasionale"] },
  "granato-almandino": { colors: ["Rosso bruno, rosso violaceo"], formula: "Fe₃Al₂(SiO₄)₃" },
  "granato-piropo": { colors: ["Rosso, rosso porpora"], formula: "Mg₃Al₂(SiO₄)₃" },
  rodolite: { colors: ["Rosa-rosso, rosso violaceo"], formula: "Soluzione solida piropo-almandino" },
  tsavorite: { colors: ["Verde"], formula: "Ca₃Al₂(SiO₄)₃ con Cr/V" },
  demantoide: { colors: ["Verde, verde giallastro"], formula: "Ca₃Fe₂(SiO₄)₃", dispersion: "Circa 0,057" },
  rubellite: { colors: ["Rosa intenso, rosso"], origin: "Varietà elbaite ricca di manganese" },
  indicolite: { colors: ["Blu, blu-verde"], origin: "Varietà blu di tormalina" },
  "tormalina-paraiba": { colors: ["Blu-verde vivido con rame"], origin: "Tormalina elbaite contenente rame; denominazione subordinata ai criteri di laboratorio" },
  tanzanite: { colors: ["Blu, viola, blu-violaceo"], origin: "Varietà blu-viola di zoisite, commercialmente associata alla Tanzania" },
  peridoto: { colors: ["Verde giallastro, verde oliva"], origin: "Varietà gemmologica dell'olivina" },
  alessandrite: { colors: ["Verde/blu-verde in luce diurna e rosso/porpora in luce calda"], origin: "Varietà cromifera di crisoberillo con cambiamento di colore" },
  "crisoberillo-occhio-di-gatto": { colors: ["Giallo, verde, bruno"], origin: "Crisoberillo cabochon con gatteggiamento da inclusioni orientate" },
  "opale-prezioso": { colors: ["Colore di fondo variabile con gioco di colore"], origin: "Silice idrata naturale con struttura ordinata" },
  "opale-di-fuoco": { colors: ["Giallo, arancio, rosso"], origin: "Opale naturale trasparente o traslucido, con o senza gioco di colore" },
  "opale-sintetico": { colors: ["Numerosi colori e pattern"], origin: "Produzione in laboratorio con struttura opalina", classification: "Sintetica" },
  "pietra-di-luna": { colors: ["Incolore, bianco, pesca, grigio con adularescenza"], origin: "Feldspato con interfacce lamellari responsabili dell'adularescenza" },
  labradorite: { colors: ["Grigio-verde con labradorescenza multicolore"], origin: "Plagioclasio con lamelle di essoluzione" },
  giadeite: { colors: ["Verde, bianco, lavanda e altri colori"] },
  nefrite: { colors: ["Verde, bianco, giallo, bruno, nero"] },
  turchese: { colors: ["Blu, verde-blu, verde"] },
  lapislazzuli: { colors: ["Blu con possibili calcite e pirite"] },
  malachite: { colors: ["Verde bandato"] },
  "perla-naturale": { origin: "Formazione naturale senza intervento umano nel mollusco", classification: "Organica" },
  "perla-coltivata": { origin: "Formazione nel mollusco dopo intervento umano", classification: "Coltivata" },
  "perla-imitazione": { origin: "Prodotto artificiale che imita la perla", classification: "Imitazione", formula: "Vetro, plastica o nucleo rivestito" },
  corallo: { colors: ["Rosso, rosa, arancio, bianco e altri colori"] },
  ambra: { colors: ["Giallo, arancio, bruno, rosso, verde o blu raro"] }
};

function defaultProtocol(name, tools) {
  return {
    title: `Protocollo operativo OroActive – ${name}`,
    steps: [
      "Registrare dichiarazione, peso, misure, stato, montatura e autorizzazione fotografica.",
      "Pulire in modo compatibile con il materiale e osservare superficie, spigoli, trasparenza, lucentezza e colore.",
      `Eseguire il primo esame con ${tools[0]} e documentare inclusioni, fratture, giunzioni o segni di trattamento.`,
      `Rilevare le proprietà disponibili con ${tools.slice(1, 4).join(", ")} senza forzare test non applicabili.`,
      "Confrontare almeno due proprietà indipendenti e verificare coerenza con simulanti, sintetici e trattamenti comuni.",
      "Se i risultati sono discordanti, la pietra è montata o l'origine/trattamento non è determinabile, fermarsi e richiedere un laboratorio qualificato.",
      "Registrare risultato preliminare, strumenti, limiti, fotografie e motivazione; non attribuire origine geografica, autenticità o valore senza evidenza adeguata."
    ],
    result_options: ["Compatibile", "Non compatibile", "Non conclusivo", "Invio a laboratorio"],
    safety_notes: ["Nessun test distruttivo", "Proteggere occhi e pelle dalle sorgenti UV", "Non usare liquidi o calore incompatibili"]
  };
}

function sourceList(name) {
  return [
    { ...CIBJO_SOURCE, accessed_on: "2026-07-29", note: `${CIBJO_SOURCE.note} Applicato a ${name}.` },
    { ...GIA_SOURCE, accessed_on: "2026-07-29", note: `${GIA_SOURCE.note} Confronto applicato a ${name}.` },
    { ...GEM_A_SOURCE, accessed_on: "2026-07-29", note: `${GEM_A_SOURCE.note} Limiti operativi applicati a ${name}.` }
  ];
}

export function completeGemologicalMaterial(seed) {
  const profileKey = PROFILE_BY_SLUG[seed.slug];
  const profile = PROFILE_DEFINITIONS[profileKey];
  if (!profile) throw new Error(`Profilo gemmologico mancante: ${seed.slug}`);
  const override = VARIANT_OVERRIDES[seed.slug] || {};
  const tools = override.tools || profile.tools;
  const colors = override.colors || ["Variabile secondo specie, varietà e composizione"];
  const treatments = override.treatments || profile.treatments;
  const classification = override.classification || seed.classification;
  const origin = override.origin || (
    ["Sintetica", "Imitazione", "Assemblata"].includes(classification)
      ? "Produzione artificiale o assemblaggio dichiarabile"
      : "Origine naturale; la provenienza geografica richiede analisi specialistica"
  );
  const summary = `${seed.name} è ${seed.mineral_name.toLowerCase()} classificato come ${classification.toLowerCase()}. Le proprietà riportate sono intervalli gemmologici di riferimento e devono essere confrontate con più osservazioni indipendenti.`;
  const description = `${seed.name}: ${profile.formula}, sistema ${profile.crystal.toLowerCase()}, durezza Mohs ${profile.mohs.join("–")}, densità ${profile.density.join("–")} g/cm³ e indice di rifrazione ${profile.ri.join("–")}. L'esame al banco è un pre-screening: origine, sintesi, trattamento e valore possono richiedere strumentazione avanzata.`;
  return {
    ...seed,
    family: profile.family,
    group_name: seed.mineral_name,
    gem_group: seed.mineral_name,
    chemical_formula: override.formula || profile.formula,
    crystal_system: profile.crystal,
    classification,
    summary,
    description,
    theory: description,
    history: override.history || `La denominazione ${seed.name} segue la nomenclatura gemmologica corrente; trattamenti, origine artificiale e assemblaggi devono essere dichiarati in modo non ambiguo.`,
    origins: [origin],
    origin,
    typical_uses: ["Gioielleria", "Collezionismo", "Formazione e confronto gemmologico"],
    typical_colors: colors,
    transparency: profile.transparency,
    luster: profile.luster,
    mohs_min: profile.mohs[0],
    mohs_max: profile.mohs[1],
    mohs_hardness: profile.mohs.join("–"),
    density_min: profile.density[0],
    density_max: profile.density[1],
    density: `${profile.density.join("–")} g/cm³`,
    specific_gravity: profile.density.join("–"),
    tenacity: profile.tenacity,
    cleavage: profile.cleavage,
    fracture: profile.fracture,
    refractive_index_min: profile.ri[0],
    refractive_index_max: profile.ri[1],
    refractive_index: profile.ri.join("–"),
    optical_character: profile.optical,
    double_refraction: profile.optical,
    birefringence: profile.birefringence,
    dispersion: override.dispersion || profile.dispersion,
    pleochroism: profile.pleochroism,
    fluorescence_long_wave: profile.fluorescence,
    fluorescence_short_wave: "Variabile; confrontare con UV lunga e riferimenti validati",
    phosphorescence: "Variabile; registrare durata e colore quando presente",
    fluorescence: profile.fluorescence,
    spectral_features: "Lo spettro può sostenere l'identificazione ma deve essere interpretato con colore, RI, densità, comportamento ottico e inclusioni.",
    optical_properties: [
      { name: "Indice di rifrazione", value: profile.ri.join("–"), limitation: "Il valore dipende da orientamento, composizione, superficie e limite dello strumento." },
      { name: "Carattere ottico", value: profile.optical, limitation: "Tensioni, aggregati e montatura possono alterare la risposta." },
      { name: "Fluorescenza", value: profile.fluorescence, limitation: "Mai diagnostica da sola." }
    ],
    inclusions: {
      typical: [override.inclusions || profile.inclusions],
      treatment_signs: treatments,
      synthesis_or_imitation_signs: profile.simulants,
      diagnostic_limit: "Un singolo carattere fotografico o microscopico non basta: richiedere coerenza tra proprietà indipendenti."
    },
    identification_difficulty: Math.max(3, Number(seed.identification_difficulty || 3)),
    difficulty_level: Number(seed.identification_difficulty || 3) >= 5 ? "Esperto" : "Avanzata",
    cleaning_precautions: profile.cleaning,
    common_treatments: treatments,
    common_simulants: profile.simulants,
    value_factors: ["Colore", "Trasparenza", "Taglio", "Peso", "Integrità", "Trattamenti dichiarati", "Origine naturale o artificiale documentata"],
    commercial_value_level: "Non stimato automaticamente; richiede esame reale, mercato, documentazione e competenza professionale.",
    recommended_tools: tools.map((name, index) => ({
      priority: index + 1,
      name,
      utility: index === 0 ? "Primo esame" : "Controllo complementare",
      look_for: index === 0 ? profile.inclusions : "Proprietà coerenti con il profilo e i relativi limiti",
      expected_result: "Dato da registrare e confrontare, non conclusione isolata",
      limitations: "Usare solo quando applicabile e secondo istruzioni dello strumento."
    })),
    operator_protocol: defaultProtocol(seed.name, tools),
    common_mistakes: [
      "Concludere da una sola proprietà o dalla sola fotografia.",
      "Ignorare montatura, contaminazione, fratture, riempimenti o rivestimenti.",
      "Attribuire origine geografica, naturale/sintetica o trattamento senza strumenti adeguati.",
      "Omettere l'esito non conclusivo e il rinvio a laboratorio."
    ],
    comparison_table: {
      columns: ["Materiale", "Confronto operativo", "Limite"],
      rows: [
        [seed.name, `${profile.mohs.join("–")} Mohs; SG ${profile.density.join("–")}; RI ${profile.ri.join("–")}`, "Intervalli di riferimento, non certificazione"],
        [profile.compare, `Confrontare RI, densità, carattere ottico, inclusioni e risposta strumentale`, "Richiede più proprietà indipendenti"]
      ]
    },
    quiz: {
      questions: [
        { id: `${seed.slug}-identity`, type: "material", prompt: `Quale combinazione di dati è compatibile con ${seed.name}?`, options: [`Mohs ${profile.mohs.join("–")}, RI ${profile.ri.join("–")}`, "Solo il colore", "Solo il peso"], correct_answer: `Mohs ${profile.mohs.join("–")}, RI ${profile.ri.join("–")}` },
        { id: `${seed.slug}-limit`, type: "procedure", prompt: "Una fotografia da sola certifica identità, origine e trattamento?", options: ["No", "Sì", "Solo se nitida"], correct_answer: "No" }
      ]
    },
    sources: sourceList(seed.name),
    review_status: "approved",
    media_status: "approved",
    active: true,
    published: true,
    founder_review_status: "approved",
    review_note: "Revisione editoriale OroActive 2026-07-29: fonti incrociate CIBJO, GIA e Gem-A; media con licenza o tavole didattiche generate."
  };
}

export const GEM_REFERENCE_SOURCES = Object.freeze([CIBJO_SOURCE, GIA_SOURCE, GEM_A_SOURCE]);
